# Generated by Django 5.0.1 on 2024-02-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0002_chatgroup_groupmembers_usercontactsbook_usermessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='groupname',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercontactsbook',
            name='hashtagid',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
