# Generated by Django 5.0.1 on 2024-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0004_alter_usercontactsbook_hashtagid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactsbook',
            name='hashtagid',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
