# Generated by Django 5.0.1 on 2024-02-06 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0005_alter_usercontactsbook_hashtagid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOnOneChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtagid', models.CharField(editable=False, max_length=128, unique=True)),
                ('addeddate', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('removedate', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to=settings.AUTH_USER_MODEL)),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserContactsBook',
        ),
    ]
