# Generated by Django 5.0.1 on 2024-02-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0007_chatgroup_hashtagid_usermessages_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneononechat',
            name='ishandshack',
            field=models.BooleanField(default=False),
        ),
    ]
